language: perl
before_install:
  - sudo apt-get install -y imagemagick libmodule-build-tiny-perl
  - sudo apt-get install -y libmodule-build-tiny-perl libplack-perl libipc-run3-perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
