language: perl
before_install:
  - sudo apt-get install -y imagemagick libmodule-build-tiny-perl
  - sudo apt-get install -y libmodule-build-tiny-perl libplack-perl
  - sudo apt-get install -y libdevel-cover-perl
  - cpanm -n Devel::Cover::Report::Coveralls
perl:
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
script:
  - perl Build.PL && ./Build && cover -test -report coveralls
